#define DEFAULT_SETTINGS {.N_THREAD_WORKERS=5, .MAX_STORAGE_SPACE=209715200, .STORAGE_BASE_SIZE= 2097152,.MAX_STORABLE_FILES=100, .SOCK_PATH=""}
#define CONFIG_NOT_FOUND 5
#define NOT_VALID_CONFIG 6

typedef struct{
    int N_THREAD_WORKERS;
    int MAX_STORAGE_SPACE;
    int STORAGE_BASE_SIZE;
    int MAX_STORABLE_FILES;
    char* SOCK_PATH;
} settings;

#ifndef CONFIG_PARSER_CONFIG_PARSER_H
#define CONFIG_PARSER_CONFIG_PARSER_H
void settings_free(settings* s);
int settings_load(settings* s, char* path);

#endif //CONFIG_PARSER_CONFIG_PARSER_H
